### ISSUE TITLE
S3 Dataplane does not register any generator function for AmazonS3 type (v0.7.1)

### ISSUE THREAD

**Issue by rafaelmag110** [eclipse-edc/Technology-Aws#401]
# Bug Report

The S3 dataplane doesn't register any generator function for the AmazonS3 destination type, hence the dataplane is not able to handle HttpData-PULL transfer types.

### Expected Behavior

An EDR can be created and a HttpData consumer-pull type transfer can be done when an AmazonS3 source is involved.

### Observed Behavior

The generatorFor() method of the DataPlaneAuthorizationService returns an error since no dataplane endpoint can be returned for the AmazonS3 data type.

![image](https://github.com/user-attachments/assets/09851d76-8071-48cc-bfd2-a4041442fad9)

## Possible Implementation

In the DataPlaneS3Extension class, register a generator function for the AmazonS3 type

**Comment by ndr-brt** [comment]
this issue was caused by a bug on the `Connector` repo:
https://github.com/eclipse-edc/Connector/issues/4310
that was fixed by:
https://github.com/eclipse-edc/Connector/pull/4315

so in the 0.8.x versions shouldn't happen (if it does, please update the issue accordingly)
If you're still on a 0.7.x version, I suggest to add this bogus call in a custom exception:
```
generatorService.addGeneratorFunction("AmazonS3", dataAddress -> endpoint);
```
(as done in `DataPlanePublicApiV2Extension`)

this fix won't be applied to 0.7.x

**Comment by rafaelmag110** [comment]
Indeed the fix shouldn't be applied to the main branch of this repo since its no longer a problem in 0.8.0 and up. However the problem persists in 0.7.1 and the bogus call, as you mentioned, would fix it.
